import Header from "@/Component/Header/Header";
import "./globals.css";
import Footer from "@/Component/Footer/Footer";
import Up from "@/Component/Up/Up";

export const metadata = {
  title: "Ahmed EL Rooby",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <Header />
        <Up />
        {children}
        
        <Footer />

      </body>
    </html>
  );
}
